gateway:
  client:
    async:
      url: http://localhost:9090/api/v1/async
    external:
      url: http://localhost:9090/api/v1/external
spring:
  jackson:
    serialization:
      indent-output: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      circuitbreakers:
        enabled: true
      ratelimiters:
        enabled: true

resilience4j:
  retry:
    instances:
      CircuitBreakerService:
        maxAttempts: 3
        waitDuration: 150ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 1.5
  circuitbreaker:
    instances:
      CircuitBreakerService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based
  timelimiter:
    metrics:
      enabled: true
    instances:
      asyncTimeLimiterApi:
        timeout-duration: 3s
        cancel-running-future: true
      timeLimiterApi:
        timeout-duration: 2s
        cancel-running-future: true
  bulkhead:
    metrics:
      enabled: true
    instances:
      bulkheadApi:
        max-concurrent-calls: 3
        max-wait-duration: 1
  ratelimiter:
    metrics:
      enabled: true
    instances:
      rateLimiterApi:
        register-health-indicator: true
        limit-for-period: 5
        limit-refresh-period: 60s
        timeout-duration: 0s
        allow-health-indicator-to-fail: true
        subscribe-for-events: true
        event-consumer-buffer-size: 50